### ISSUE TITLE
Feature Request - set amount of links to show when using debrid

### ISSUE THREAD

**Issue by zippyy** [aymene69/stremio-jackett#22]
I noticed the # of results is only available as a setting when selecting torrent, I use debrid and even tried setting that setting before selecting debrid and putting in my api but I am still only getting 1 link per show/film even though I have many trackers in my jackett instance.

**Comment by aymene69** [comment]
When using a debrid service, you can currently only get one result. It may be increased in the future

**Comment by aymene69** [comment]
Although, we may only show them with instant availability, not downloading each X results

**Comment by aymene69** [comment]
Fixed in v1.1.3 release

**Comment by trulow** [comment]
Even after setting the "Number of results per search" value. I'm still getting an issue were it's only returning one result.

**Comment by hyoretsu** [comment]
@trulow fixed in v1.1.6

**Comment by trulow** [comment]
@hyoretsu I appreciate it. I've upgraded and deployed the latest release and can confirm that it works.
