### ISSUE TITLE
[Bug] TypeError: Cannot set properties of undefined (setting 'seeders')

### ISSUE THREAD

**Issue by 9acca9** [aymene69/stremio-jackett#82]
**Describe the bug**
I search for a movie in stremio. The addon in stremio return "No results found".

**To Reproduce**
Search for a movie in stremio app.

**Expected behavior**
I was expecting a movie.

**Screenshots**
![imagen](https://github.com/aymene69/stremio-jackett/assets/25393371/1f6c52ae-1826-4d9c-b6fd-3c264e315f45)

**Your system info (please complete the following information):**
 - OS: Manjaro Linux
 - Version (i use git clone and when run npm start i see version is 2.0.0... but i found that the release here is 2.0.1 (i also download that release and try it... but still says 2.0.0(probably a typo)))
 - Node 
 - Torrent

A log:
```
npm start                                       ✔  panchines@manjaro 

> stremio-addon-jackett@2.0.0 start
> node dist/addon/index.cjs

Server is running at http://localhost:3000
Movie request.
ID: tt0286751
Name: Pulse
http://www.xxxxxxxxxx.xyz
Searching on Jackett, will return torrents...
Searching on cache...
No cache
Cache search done.
No cache
https://www.xxxxxxxx.xyz/jackett/api/v2.0/indexers/all/results/torznab/api?apikey=<private>&t=movie&cat=2000&q=Pulse&year=2001
Sorting by locale + quality...
Torrent info: 2001 promo for Earth Pulse
TypeError: Cannot set properties of undefined (setting 'seeders')
    at jackettSearch (/home/panchines/stremio-jackett/dist/addon/index.cjs:102:10581)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchResults (/home/panchines/stremio-jackett/dist/addon/index.cjs:130:328)
    at async /home/panchines/stremio-jackett/dist/addon/index.cjs:132:79


Thanks for taking the time!
```

**Comment by aymene69** [comment]
Fixed

**Comment by 9acca9** [comment]
Thanks for taking the time.
But, still not working for me. Now it give me this:
```
Torrent info: Pulse (2001) [1080p] [BluRay] [2.0] [YTS] [YIFY]
TypeError: Cannot read properties of undefined (reading 'title')
    at jackettSearch (/home/panchines/stremio-jackett/dist/addon/index.cjs:103:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchResults (/home/panchines/stremio-jackett/dist/addon/index.cjs:130:330)
    at async /home/panchines/stremio-jackett/dist/addon/index.cjs:132:79
```

Do you want that i open a new bug?

**Comment by aymene69** [comment]
fixed
