### ISSUE TITLE
[Bug] Results returns don't agree with the indicated search (for some TV shows)

### ISSUE THREAD

**Issue by xancandal** [aymene69/stremio-jackett#96]
At the last version 2.1.6. I have detected the following error, with some series (not all). The results that Jackett returns for some series do not agree with the indicated search.

For example, if you search for S01E01 of the Andor series, the following results appear: S01E02, S01E04, S01E02, S01E01 (this is correct), S01E03, etc.
 
With S01E03 of the series "The Continental" the following results appear instead: S01 COMPLETE, S01E01, S01E02, S01E01, ,S01E3 (this is correct), S01 COMPLETE SEASSON, etc.

If you do a manual search within Jackett this error is not reproduced.

I attach screenshots of these results:
![IMG_1892](https://github.com/aymene69/stremio-jackett/assets/1079504/38d60c44-8dae-41c6-9969-2ce8c1417131)
![IMG_1893](https://github.com/aymene69/stremio-jackett/assets/1079504/696b33eb-f5ea-41d8-8fc1-1e5d878abae4)
![IMG_1894](https://github.com/aymene69/stremio-jackett/assets/1079504/fdc25a26-1f19-4126-8e9b-550305036854)
![IMG_1895](https://github.com/aymene69/stremio-jackett/assets/1079504/b1a375aa-400c-4d7d-b491-d306d3bb4927)
![IMG_1896](https://github.com/aymene69/stremio-jackett/assets/1079504/56b8ad31-a5e2-4135-8c82-a98c7a73c083)
![IMG_1897](https://github.com/aymene69/stremio-jackett/assets/1079504/1adfd6bd-35c0-4222-b012-89ecc7dcaded)
![Screenshot_5](https://github.com/aymene69/stremio-jackett/assets/1079504/c8b76a73-a75c-4546-9e9d-1c2d587ceec7)

**Comment by wogam** [comment]
Have you put in your TMDb api key during set up?

**Comment by xancandal** [comment]
Yes, I have put my TMDb api key. Also, I have tested removing the TMDb api key but the bug remains.

**Comment by aymene69** [comment]
Fixed

**Comment by xancandal** [comment]
Unfortunately, the error still appears in version 3.0.6
![IMG_1951](https://github.com/aymene69/stremio-jackett/assets/1079504/1034f219-30aa-41d8-8518-325735109871)
